spring:
  application:
    name: tms-service-configuration
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true

server:
  port: 9091


