spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/tms-service-configuration
    username: root
    password: root

logging:
  level:
    'com.amalvadkar.tms.configuration' : debug
    'org.hibernate.stat' : debug
    'org.hibernate.SQL' : debug
    'org.hibernate.orm.jdbc.bind' : trace
